language: Java
notifications:
  email:
    recipients:
      - janpietrzak00@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

after_success:
  - mvn --quiet clean site

before_deploy:
  - "mvn -DskipTests package"

deploy:
  provider: releases
  api_key: $github_token
  skip_cleanup: true
  file: target/TextTransformer.jar
  on:
    tags:
      true